### PR TITLE
Terminal selection

### PR DESCRIPTION
**Pull request by TomTranter**

### CODE REVIEW

**Comment by TomTranter** [comment]
@wigging check to see if this breaks any examples you've changed again. I could just merge and you could pull it through to your branch. Also, what do you think about the changes I've made here? Don't think there's any backwards incompatibility.

**Review by wigging — APPROVED** [review]
Everything looks good. Interesting how the terminal locations affect current. Is it possible to add color to the circuit diagrams to easily distinguish the terminals from the bus bars? Also, keep in mind that in script files you should explicitly show the plot figure `lp.show_plots()` otherwise the figure will not appear when the file is run from the terminal.

**Comment by TomTranter** [comment]
@wigging I've made some more stylistic updates including terminal colors and some functional ones too. The lcapy circuit can actually be used for a bunch of stuff itself although I only used it for drawing but it might be useful to people to have a direct handle of so I move it to netlist_utils out of the draw function. This also makes it easier to test as generating the circuit is quick but plotting not. I should probably put in some warnings that the draw method only works properly for the generated square netlists and only quite small ones at that - what do you think? Add a default warning that shows every time which could get annoying. The issue is once you have the netlist you don't necessarily know where it came from and whether it will draw ok or not.

**Comment by wigging** [comment]
@TomTranter I would add the warning and possible issues in the docstring for the netlist. You could also mention them in an example script or notebook about drawing the circuit.

**Pull request merged**
