### PR TITLE
Add notebook tests

### PR DESCRIPTION
**Pull request by priyanshuone6**
Add tests and change root directory

### CODE REVIEW

**Comment by priyanshuone6** [comment]
I think we need to skip coverage for tests

**Comment by TomTranter** [comment]
Hi @priyanshuone6 so the notebook test is just looking for the install on the first line? You can test the whole notebook using nbconvert and looking for return codes - this would probably slow down the tests a lot though. Is this just what we do with PyBaMM?

**Comment by priyanshuone6** [comment]
It will open the notebook as a text and search for the install command. In PyBaMM, we test this the same way, and we also convert the notebook to python using nbconvert to test the whole notebook.
Should I also test the whole notebook?

**Comment by TomTranter** [comment]
Yes although some cells in one of the notebook are meant to fail to demonstrate bad arguments to a function so maybe we can catch those errors or delete those cells as it's not that important

**Review by TomTranter — CHANGES_REQUESTED** [review]
Can you add the full notebook tests and remove the failing cells please

**Comment by priyanshuone6** [comment]
Yes, I am working on it

**Comment by priyanshuone6** [comment]
Notebooks are failing due to Issue #85
Will need to merge main after PR #89 is merged

**Pull request merged**
