### PR TITLE
Use Conda in GitHub Actions

### LINKED ISSUE #74: GitHub Action workflow to check conda environment
Can someone add a GitHub Action to build and check the conda environment? I don't have permission to update the workflow in this repository but I believe it would be something like this:

```yaml
  build:
    needs: style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
```

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Fixes #74 

## Changes/Additions
- CI now also install dependencies and runs tests in a conda environment
- flake8's max-line-length changed to 89 (as it is in the .flake8 file)
- Coverage report is now generated using conda
- Minor style fixes

### CODE REVIEW

**Comment by TomTranter** [comment]
I think it would be good to have both. Thanks

**Comment by wigging** [comment]
As I mentioned in the issue, you should add it to what you did before. The idea is to make sure liionpack builds correctly using the pip approach and that it also builds correctly using the conda approach.

**Review by wigging — COMMENTED** [review]
The coverage package is installed with pip but it is run in the conda environment. If it's intstalled with pip will it be seen in the conda environment? I suggest doing the coverage stuff all in the same environment.

**Review by wigging — APPROVED** [review]
👍 approved

**Comment by Saransh-cpp** [comment]
```
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
```
I think Codecov isn't detecting the coverage report because it was created in the conda environment. Let me try doing all the coverage stuff outside the conda environment.

**Comment by Saransh-cpp** [comment]
Everything working now!

**Pull request merged**
