### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by TomTranter**

### CODE REVIEW

**Comment by TomTranter** [comment]
@Saransh-cpp after some playing I switched to using conda to build the packages instead of pip. I added some specific mkdocs dependencies to the environment.yml though. Is there a way to only install these with a [docs] type argument?

**Comment by Saransh-cpp** [comment]
AFAIK conda doesn't support adding tags or arguments for dependencies. [This](https://stackoverflow.com/a/70089549/14746647) answer suggests adding a new `environment.yml` file (maybe named `environment.docs.yml`) with only the docs requirements and using both of them to setup an environment for docs.

**Comment by TomTranter** [comment]
The other equally unappealing option would be to just have a separate yml for docs with all the packages duplicated and the extra ones included.

**Comment by TomTranter** [comment]
I have submitted a question on read the docs about running bespoke conda commands

**Pull request merged**
