### PR TITLE
Migrate to hatch + modern python packaging

### PR DESCRIPTION
**Pull request by Saransh-cpp**
I tested this locally, and both `pip` and `conda` builds work without any errors! To be on the safer side, could someone please test it out locally with `pip` and with `conda` (@wigging)?

### CODE REVIEW

**Comment by wigging** [comment]
@Saransh-cpp I can try to install this with conda and will let you know if I have any issues. Also, what is hatch?

**Comment by Saransh-cpp** [comment]
[`hatch`](https://hatch.pypa.io/latest/) is a modern build backend that handles packaging and building stuff for a python library. Most of the Python projects right now use `setuptools` which was the original replacement for the broken `distutils` backend, but the development of `hatch` is picking up more speed than the development of `setuptools` in terms of meeting the new PEPs. For instance, the editable install without a `setup.py` file was just introduced in `setuptools`, whereas it already exists in `hatch` - see https://peps.python.org/pep-0660/) - 

(took more than a year to be introduced in the main `setuptools` repository) -

image

This will not affect the frontend or the user-facing functionalities in any way, but now `hatch` would be handling the packaging stuff of `liionpack` instead of `setuptools`.

**Comment by wigging** [comment]
I created a conda environment using the `hatch` branch and ran the `basic_16p2s.py` example and everything works fine.

**Comment by wigging** [comment]
Regarding modern approaches to packaging in Python. Using a `src` directory is the preferred approach these days.

**Comment by TomTranter** [comment]
Hi @Saransh-cpp looks good thanks for this. I tested conda install locally too

**Pull request merged**
