### PR TITLE
Update example scripts

### PR DESCRIPTION
**Pull request by wigging**
I updated all of the example scripts to run with the latest version of liionpack (as of v0.2-beta). I could not get the drive_cycle_comparison.py example to work. I get an error related to the pybamm.Simulation about an unhashable numpy array type.

### CODE REVIEW

**Comment by wigging** [comment]
There is an issue with PyBaMM when providing a drive cycle Experiment to the Simulation class. I'll submit an issue on the PyBaMM repo before moving forward with this pull request.

**Comment by wigging** [comment]
@TomTranter You submitted an [issue](https://github.com/pybamm-team/PyBaMM/issues/1788) related to my previous comment. The issue was closed on PyBaMM but I can't get the example to solve. Were you able to get the `drive_cycle_comparison.py` script to solve?

**Comment by TomTranter** [comment]
@wigging yes it works for me. Have you updated PyBaMM lately?

**Comment by wigging** [comment]
The V1 and V2 arrays are different lengths for the load_4p1s example. This causes an error with `np.allclose`.

**Comment by TomTranter** [comment]
Thanks for spotting that @wigging . I had changed the way the terminals are defined and before it had 2 resistors to make the up and across wires in the circuit diagram but that was messy and is now unnecessary.

**Pull request merged**
