### PR TITLE
Issue 41 benchmarks

### PR DESCRIPTION
**Pull request by brosaplanella**
In principle, this should setup the workflows for the benchmarks. I tried the benchmarks on my computer and they worked well (see https://pybamm-team.github.io/liionpack-bench/). At the moment there is only one data point so there is no graph available.

### CODE REVIEW

**Comment by TomTranter** [comment]
Thanks Ferran, could you add a section on benchmarks to the contributing document explaining how they run a little bit. I'm not that familiar with how it works so how would I test this PR? Thanks

**Comment by brosaplanella** [comment]
I have added a CONTRIBUTING doc with benchmarks (and some other things that were applicable to `liionpack` straight out of PyBaMM's document). I can improve it later on.

**Comment by TomTranter** [comment]
@brosaplanella there was already a contributing.md in the docs subfolder which I had edited from pybamm but removed quite a bit. Could you put your changes there please

**Review by TomTranter — CHANGES_REQUESTED** [review]
See comment

**Comment by brosaplanella** [comment]
Sorry, didn't see it! Let me know if it is OK now :)

**Review by TomTranter — APPROVED** [review]

**Comment by TomTranter** [comment]
Thanks a lot @brosaplanella

**Pull request merged**
