### PR TITLE
Update conda environment

### PR DESCRIPTION
**Pull request by wigging**
I updated the conda environment file for installing the latest version.

### CODE REVIEW

**Comment by TomTranter** [comment]
And dask and distributed?

**Comment by TomTranter** [comment]
You also need distributed

**Comment by wigging** [comment]
Doing `conda install dask` installs `distributed`.

**Comment by TomTranter** [comment]
Should we change github actions to test installing this way?

**Comment by wigging** [comment]
Yeah, it looks like the actions are setup for a pip install. So whoever configured the actions should do one for a conda install too. They should be able to use the new install instructions in the README for the proper steps.

**Comment by TomTranter** [comment]
I'm not very good with github actions would you mind taking care of it?

**Pull request merged**
