### PR TITLE
Test only on pybamm stable

### PR DESCRIPTION
**Pull request by Saransh-cpp**

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
This is failing as expected. This should be ready to merge when a new version of PyBaMM is released. After this is merged, it would be safe to delete the main branch as our primary branch will now be develop.

One more comment, you will have to update the version pin of pybamm if the new release of liionpack will not be compatible with the older pybamm versions.

**Comment by TomTranter** [comment]
Thanks alot for you help on this @Saransh-cpp. I figured out how to activate pre-commit on the other PR

**Comment by Saransh-cpp** [comment]
Great! I'll get this up!

**Comment by Saransh-cpp** [comment]
@TomTranter this looks good now. Everything will now shift only to the develop branch, every release must be made through develop, and every PR should go into develop. This also means that we will only test on the stable version of PyBaMM. Everything is passing right now, but whenever you make some changes to support a new breaking release of PyBaMM, you must bump the PyBaMM required version in `pyproject.toml`.

**Comment by rtimms** [comment]
thanks @Saransh-cpp ! IMO we should pin a PyBaMM version since the liionpack dev cycle is slower. My preference would be to pin to 23.3 for now since there were a lot of changes (in particular dimensional models), fix bugs and make a liionpack release.

Then we can take a step back and plan out the next steps (integrate into PyBaMM or keep it separate).

**Pull request merged**
