### PR TITLE
Implement Dask solver

### PR DESCRIPTION
**Pull request by TomTranter**

### CODE REVIEW

**Comment by TomTranter** [comment]
N.B just creating the PR now to see if we get any broken tests and merge issues

**Comment by wigging** [comment]
Is it too late to move the Ray code into its own branch? There can be a `dask` branch and a `ray` branch.

**Comment by TomTranter** [comment]
@wigging I'm minded to just merge it in and make a new branch for further development. It should leave the existing functionality unchanged

**Comment by wigging** [comment]
@TomTranter Let me remove some code before you merge with the main branch. I think there are some functions I added early on that aren't used for anything.

**Comment by wigging** [comment]
@TomTranter Nevermind, I can cleanup the code later. Go ahead and merge if you want to.

**Comment by TomTranter** [comment]
@wigging I've refactored the solvers into manager classes living in solvers.py. The old solve method in solver_utils now just wraps each one passing in a different manager string e.g. "casadi", "ray". A lot of the functions in solver_utils can now be cleaned up and I'll do that but let me know your thoughts. The generic_manager now has most of the solve logic and there are subclassed setup, step, get_output and cleanup methods. It all works with just one generic_actor now I've reconfigured it slightly. I guess we could also provide warnings if nproc is 1 to use the casadi manager it will be much slower to use the others with all the initialisation overhead

**Pull request merged**
