### PR TITLE
Fix notebooks, add tests

### PR DESCRIPTION
**Pull request by priyanshuone6**
Fix notebooks, add tests

### CODE REVIEW

**Comment by TomTranter** [comment]
Hey @priyanshuone6 do I take it now that notebooks need to conform to Pep8?

**Comment by priyanshuone6** [comment]
I don't think it is required. We could add a %nb-black command in the 1st cell to make sure it adheres pep

**Comment by TomTranter** [comment]
The fixes look like style mostly - is that what you were fixing?

**Comment by priyanshuone6** [comment]
Yes and one notebook was raising type error due to scale_factor
image

**Comment by TomTranter** [comment]
Great! Thanks @priyanshuone6

**Pull request merged**
