### PR TITLE
Documentation doesn't render properly

### PR DESCRIPTION
**Pull request by Saransh-cpp**
As liionpack is using mkdocstrings, the docstring format should be a bit different than that of PyBaMM. Right now the documentation for `read_netlist` looks like this -

image

And after editing the docstring, it looks like this -

image

The only weird thing here is that I have to add the type of parameters in the python code itself to make mkdocstrings fill up the `Type` column, like this -
```py
def read_netlist(
    filepath: str,
    Ri: float = 1e-2,
    Rc: float = 1e-2,
    Rb: float = 1e-4,
    Rl: float = 5e-4,
    I: float = 80.0,
    V: float = 4.2,
):
```
and in the end, the documentation improves a lot. Should I do this for all the functions?

### CODE REVIEW

**Comment by TomTranter** [comment]
hmm that's a bit of a pain. There might be another work around or we could switch to some other document generator.

**Comment by TomTranter** [comment]
I used mkdocstrings but there are other options listed here https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building

**Comment by TomTranter** [comment]
Although reading the docs for one of the alternatives also recommends including types ... :( https://github.com/AlexandreKempf/automacdoc/
I guess it would also be useful for any gui interface that we might build

**Comment by Saransh-cpp** [comment]
So should I go ahead with this?

**Comment by TomTranter** [comment]
Yeah that looks better. Can you see if there is a mathjax plugin too for rendering the equations and symbols

**Comment by Saransh-cpp** [comment]
I found [Arithmatex](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/), tried it out and it works well.

**Review by TomTranter — APPROVED** [review]

**Pull request merged**
